
name: Build and Deploy to Docker

on:
  push:
    branches:
      - main  # Adjust this based on your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use ubuntu-latest for compatibility with Amazon Linux AMI

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Specify the Java version you want to use

      - name: Build with Maven
        run: mvn clean package

      # Add more steps for Docker build and deploy here
